# -*- coding: utf-8 -*-
"""dataprep_CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k65Tl2WSLEJY3jgt0Bqx1Ec3Cky3IYC1
"""

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

data_v = pd.read_csv("drive/My Drive/INTERN/socis/CNN/clean_images_to_csv/image_clean.csv",dtype=object,error_bad_lines=False )
le = preprocessing.LabelEncoder()

data_v['power_state_spec'] = le.fit_transform(data_v['power_state_spec'].astype('str'))

data_v['power_state_value'] = le.fit_transform(data_v['power_state_value'].astype('str'))
k = data_v["dir"].astype('str') 
q = len(k)
for i in range(q):
  
  l = len(k[i])
  if(l==1):
   
#     print(k[i])
    k[i]= "00"+str(k[i])
 
#     print(k[i])
#     print("----")
  if(l==2):
#     print(k[i])
    k[i]="0"+str(k[i])
    
#     print(k[i])
#     print("----")
  
  
leng = len(k)
# print(leng)
# print(type(k))
data_v["dir"] = k
# print(k)
# print(data_v["dir"])
data_v["id"] = data_v["id"].map(str) +"_"+k
print(data_v["id"])

arr_v = data_v.values

arr_v = arr_v[0:]
print(arr_v)

ON_list =[]
OFF_list = []
for i in range(len(arr_v)):
    s = arr_v[i][1]
    s = str(s)
    
#     print(type(st))
    if s.find("N") == -1:
        OFF_list.append(arr_v[i])
    
    else:
        ON_list.append(arr_v[i])
# calculating for ON
print(len(ON_list),"ON")
print(len(OFF_list),"OFF")
arr_on_v = np.array(ON_list)
arr_off_v = np.array(OFF_list)
print(arr_on_v)
print(arr_off_v)

dataset_on = pd.DataFrame({'S.no': arr_on_v[:, 0], 'File_id': arr_on_v[:, 1], 'Path': arr_on_v[:,3], 'power_state_value':arr_on_v[:,4],'current_rise/fall_time_value (mS)':arr_on_v[:,5],'current_stabilised_value (mA)': arr_on_v[:,6],'current_max/min_value (mA)':arr_on_v[:,7]  })
dataset_on.head()

dataset_off = pd.DataFrame({'S.no': arr_off_v[:, 0], 'File_id': arr_off_v[:, 1], 'Path': arr_off_v[:,3], 'power_state_value':arr_off_v[:,4],'current_rise/fall_time_value (mS)':arr_off_v[:,5],'current_stabilised_value (mA)': arr_off_v[:,6],'current_max/min_value (mA)':arr_off_v[:,7]  })
dataset_off.head()

df_on = dataset_on.iloc[:,2:7].copy() 
df_on.head()

df_on.to_csv("drive/My Drive/INTERN/socis/CNN/clean_images_to_csv/on_clean.csv", index=False, sep=',')

df_off = dataset_off.iloc[:,2:7].copy() 
df_off.head()
df_off.to_csv("drive/My Drive/INTERN/socis/CNN/clean_images_to_csv/off_clean.csv", index=False, sep=',')

df_off.head()

